version: '2'
services:
  ping:
    container_name: ping
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - ICMP_METRICS_PORT=9346
      - ICMP_COLLECTION_INTERVAL=60
    ports:
      - "9346:9346"
    volumes:
      - ./example.conf.yml:/etc/ping/hosts.yml